export const NEXT_PUBLIC_KAKAO_LOGIN_REDIRECT_URI = process.env.NEXT_PUBLIC_KAKAO_LOGIN_REDIRECT_URI!;

export const KAKAO_LOGIN_CLIENT_ID = process.env.KAKAO_LOGIN_CLIENT_ID!;
export const KAKAO_LOGIN_CLIENT_SECRET = process.env.KAKAO_LOGIN_CLIENT_SECRET!;
